service: younique-wedding-api-2

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-younique-wedding

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1

  environment:
    tableName: ${self:custom.tableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [YouniqueWeddingTable, Arn]

functions:
  getTodos:
    handler: functions/getTodos.main
    events:
      - http:
          path: todos
          method: get
          cors: true
          authorizer: aws_iam

  createTodo:
    handler: functions/createTodo.main
    events:
      - http:
          path: todos
          method: post
          cors: true
          authorizer: aws_iam

  deleteTodo:
    handler: functions/deleteTodo.main
    events:
      - http:
          path: todos
          method: delete
          cors: true
          authorizer: aws_iam

  updateTodo:
    handler: functions/updateTodo.main
    events:
      - http:
          path: todos
          method: put
          cors: true
          authorizer: aws_iam

  getGuests:
    handler: functions/getGuests.main
    events:
      - http:
          path: guests
          method: get
          cors: true
          authorizer: aws_iam

  createGuest:
    handler: functions/createGuest.main
    events:
      - http:
          path: guests
          method: post
          cors: true
          authorizer: aws_iam

  deleteGuest:
    handler: functions/deleteGuest.main
    events:
      - http:
          path: guests
          method: delete
          cors: true
          authorizer: aws_iam

  updateGuest:
    handler: functions/updateGuest.main
    events:
      - http:
          path: guests
          method: put
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/database-table.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
