service: younique-wedding-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-central-1

  environment:
    tableName: todos

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  createTodo:
    handler: createTodo.main
    events:
      - http:
        path: todos
        method: post
        cors: true
        authorizer: aws_iam

  getTodos:
    handler: getTodos.main
    events:
      - http:
        path: todos
        method: get
        cors: true
        authorizer: aws_iam

  deleteTodo:
    handler: deleteTodo.main
    events:
      - http:
        path: todos/{id}
        method: delete
        cors: true
        authorizer: aws_iam
